In [1]:
# Importing the necessary libraries
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

import numpy as np
import warnings
warnings.filterwarnings("ignore")

#### Creating the models with train_test_split (i.e Without K-fold cross validation)

In [2]:
# Loading the datasets
digits = load_digits()

In [3]:
# Splitting the dataset into train and test data.
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [4]:
# Logistic Regression
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test, y_test)

0.9648148148148148

In [5]:
# SVM
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.3388888888888889

In [6]:
# RandomForest
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9518518518518518

### KFold cross validation

Example

In [7]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
for train_index, test_index in kf.split(['a','b','c','d','e','f','g','h','i']):
    print (train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Applying KFold on digit dataset

In [9]:
def score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test,y_test)

In [10]:
folds = StratifiedKFold(n_splits=3)

logistic_scores = []
svm_scores = []
rf_scores = []

for train_index,test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    logistic_scores.append(score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
    svm_scores.append(score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    rf_scores.append(score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))

In [11]:
logistic_scores

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [12]:
svm_scores

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [13]:
rf_scores

[0.9398998330550918, 0.9432387312186978, 0.9181969949916527]

### Using CrossValidation function

In [14]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data, digits.target, cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [15]:
cross_val_score(SVC(gamma='auto'),digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [16]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=3)

array([0.92988314, 0.95492487, 0.91986644])

### Parameter tuning of RandomForest Classifier

In [17]:
score_1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(score_1)

0.878140906269398

In [18]:
score_2= cross_val_score(RandomForestClassifier(n_estimators=10),digits.data, digits.target, cv=10)
np.average(score_2)

0.9237802607076349

In [19]:
score_3 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(score_3)

0.9354531346989446

In [20]:
score_4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(score_4)

0.9437895716945995